### ISSUE TITLE
RasaFactory implementation improvements

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/resource-availability-status-api#12]
Some small suggestions for improving the RasaFactory implementation ([ACDHRasaFactory](https://github.com/clarin-eric/resource-availability-status-api/blob/master/src/main/java/eu/clarin/cmdi/rasa/helpers/impl/ACDHRasaFactory.java)) to make it better suited for use in a library context:

- do not initialise the database on construction, but introduce an `init` or `connect` method (also add to the `RasaFactory` interface?)
- do not swallow the SQL exception upon database initialisation
- get rid of the [ConnectionProvider](https://github.com/clarin-eric/resource-availability-status-api/blob/master/src/main/java/eu/clarin/cmdi/rasa/helpers/ConnectionProvider.java) interface and just use `java.util.function.Supplier<java.sql.Connection>`

**Comment by wowasa** [comment]
done
