### ISSUE TITLE
Connection might not be closed

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/resource-availability-status-api#22]
In the stream methods of resource implementation classes the connections are not closed of on exception occurs before passing the resultset to the stream. 
For example class ACDHCheckedLinkResource, lines 92-94. Most likely would be an error in the sql statement which would then lead to an unclosed connection

**Comment by twagoo** [comment]
This should be implemented with try(-catch)-finally to avoid connection leaking in case an unchecked exception occurs. And the caught SQL Exceptions should probably be re-thrown.

**Comment by wowasa** [comment]
fixed in v. 4.0.0
