### ISSUE TITLE
new tables for linkchecker webservice

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/resource-availability-status-api#41]
- user (id, email, token, quota)
- priority (id, url_id)
- lot (id, charging_date, user_id)
- url_lot (id, lot_id, url_id)

**Comment by twagoo** [comment]
Couple of small point:
* What does `lot` stand for? 
* Can we use the name `client` instead of `user`?
* Instead of `charging` I think it would be clearer to use `ingestion` or `submission` (more standard terminology I think)

**Comment by wowasa** [comment]
The issue is taken into account for the initial version of the  [curation persistence API (cpa)](https://github.com/clarin-eric/curation-persistence) , which is going to replace this resource-availability-status-API.
